### ISSUE TITLE
server.dockerfile container initialisation

### ISSUE THREAD

**Issue by sakshamshahu** [sakshamshahu/AIEDS#3]

**Comment by H-SM** [comment]
The server container in the Docker setup is encountering an issue where nodemon is attempting to start the server with the wrong path, resulting in a **"Cannot find module" error.**

When the server container starts, `nodemon` initiates the server startup process with the command [nodemon] starting `node dist/index.js index.js`. However, this command is incorrect, as it is trying to locate the server's entry point at /client/index.js, which doesn't exist. Consequently, the server crashes with the error Error: `Cannot find module '/client/index.js'.`

The Docker setup consists of two services: `aides-client` and `aides-server`. The client service is successfully starting, as indicated by the message Compiled successfully!, while the server service is encountering the mentioned error.

![Screenshot_2024-03-12_21-27-40](https://github.com/sakshamshahu/AIEDS/assets/98532264/1e4bee47-97b7-452a-8860-a3c759238e84)

**Comment by sakshamshahu** [comment]
The issue has been resolved in the recent merge #46 & #47 @H-SM @
<img width="1454" alt="Screenshot 2024-04-24 at 5 24 38 PM" src="https://github.com/sakshamshahu/AIEDS/assets/101853380/4b1e8cb0-a1aa-4c36-88cb-1d0efd43a7c0">
